/* test_core.c -- audiofile_core with no Pd anywhere near it.
 *
 * The fixtures are generated by tests/make_fixtures.py: a 441 Hz sine at
 * 44100 Hz, so frame n holds 0.5 * sin(2*pi*n/100) whatever the container.
 * That is what lets a test say where a seek landed.
 *
 * Part of pd-audiofile. SPDX-License-Identifier: Zlib
 */

#include "audiofile_core.h"
#include "af_platform.h"

#include <stdarg.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>

#define FIXTURE_RATE    44100.0
#define FIXTURE_FRAMES  22050
#define FIXTURE_PERIOD  100.0     /* frames per cycle of the fixture sine */
#define FIXTURE_AMP     0.5

/* M_PI is not in standard C, and which compilers offer it depends on how the
 * build asks for its language. */
#define AF_PI           3.14159265358979323846

static const char *g_dir = "fixtures";
static int g_pass, g_fail, g_skip;
static const char *g_case = "";

static char *fixture(const char *name)
{
    static char path[1024];
    snprintf(path, sizeof(path), "%s/%s", g_dir, name);
    return path;
}

static int exists(const char *path)
{
    FILE *f = fopen(path, "rb");
    if (f == NULL) return 0;
    fclose(f);
    return 1;
}

static void ok(int condition, const char *fmt, ...)
{
    va_list ap;
    va_start(ap, fmt);
    if (condition) {
        g_pass++;
    } else {
        g_fail++;
        printf("  FAIL  [%s] ", g_case);
        vprintf(fmt, ap);
        printf("\n");
    }
    va_end(ap);
}

static void skip(const char *what)
{
    g_skip++;
    printf("  skip  %s\n", what);
}

static void begin(const char *name)
{
    g_case = name;
    printf("- %s\n", name);
}

/* ------------------------------------------------------------------ */
/* Reading, the way a perform routine would                            */
/* ------------------------------------------------------------------ */

typedef struct {
    size_t frames;
    int    eofs;
    int    underflows;
    int    timed_out;
} af_drain;

/* Pulls up to `limit` frames in blocks of `block`, waiting when nothing is
 * buffered and giving up after `budget_ms` so that a stream that stops reading
 * ahead fails the test. */
static af_drain drain(af_stream *s, float *out, size_t limit,
                      size_t block, size_t channels, int budget_ms)
{
    af_drain d;
    int idle_ms = 0;

    memset(&d, 0, sizeof(d));

    while (d.frames < limit) {
        size_t want = limit - d.frames;
        size_t got;

        if (want > block) want = block;
        got = af_stream_read(s, out ? out + d.frames * channels : NULL, want);

        {
            unsigned events = af_stream_take_events(s);
            if (events & AF_EVENT_EOF)       d.eofs++;
            if (events & AF_EVENT_UNDERFLOW) d.underflows++;
        }

        if (got == 0) {
            if (d.eofs > 0) break;
            af_sleep_ms(1);
            if (++idle_ms > budget_ms) { d.timed_out = 1; break; }
            continue;
        }
        idle_ms = 0;
        d.frames += got;
    }
    return d;
}

/* Read, waiting the way an audio thread would, until a block comes back whole.
 * A whole block clears the stalled state, so a stall raised after this is a
 * new one. */
static int settle(af_stream *s, float *buf, size_t frames)
{
    int waited = 0;
    while (af_stream_read(s, buf, frames) < frames) {
        af_sleep_ms(1);
        if (++waited > 2000) return 0;
    }
    af_stream_take_events(s);
    return 1;
}

/* out is only used when it is non-NULL, so a discard needs a real buffer. */
static float *scratch_buffer(size_t frames, size_t channels)
{
    float *p = (float *)calloc(frames * channels, sizeof(float));
    if (p == NULL) { fprintf(stderr, "out of memory\n"); exit(2); }
    return p;
}

static double expected_sample(double frame)
{
    return FIXTURE_AMP * sin(2.0 * AF_PI * frame / FIXTURE_PERIOD);
}

/* The linear resampler holds a frame of history and primes itself with a
 * couple of zeros, so the block that comes back after a seek is the file at
 * the seek target give or take a small lag. Reporting the best lag and its
 * error separates "landed in the wrong place" -- which is the failure worth
 * catching -- from "off by one frame".
 *
 * `step` is how many file frames each output frame advances by: 1 at speed 1,
 * 2 at speed 2, and so on. Callers skip the first few output frames, which are
 * the resampler filling its history. */
static double phase_error(const float *buf, size_t frames, double start_frame,
                          double step, int *best_lag)
{
    double best = 1e9;
    int lag;

    for (lag = -3; lag <= 3; lag++) {
        double worst = 0.0;
        size_t i;
        for (i = 0; i < frames; i++) {
            double want = expected_sample(start_frame + ((double)i + lag) * step);
            double err  = fabs((double)buf[i] - want);
            if (err > worst) worst = err;
        }
        if (worst < best) {
            best = worst;
            if (best_lag) *best_lag = lag;
        }
    }
    return best;
}

/* The first frames out of a freshly reset resampler are its own history, not
 * the file's. */
#define AF_PRIME 8

/* ------------------------------------------------------------------ */
/* Probing                                                             */
/* ------------------------------------------------------------------ */

static void probe_case(const char *name, double rate, uint64_t frames,
                       uint32_t channels, const char *format)
{
    af_info   info;
    af_status status;
    char      label[256];

    if (!exists(fixture(name))) { skip(name); return; }

    snprintf(label, sizeof(label), "af_probe %s", name);
    begin(label);

    status = af_probe(fixture(name), &info);
    ok(status == AF_OK, "status %s", af_status_string(status));
    if (status != AF_OK) return;

    ok(info.samplerate == rate, "samplerate %g, wanted %g", info.samplerate, rate);
    ok(info.channels == channels, "channels %u, wanted %u", info.channels, channels);

    /* Lossy encoders pad; the container's own idea of the length is exact. */
    if (frames > 0) {
        ok(info.frames == frames, "frames %llu, wanted %llu",
           (unsigned long long)info.frames, (unsigned long long)frames);
    }
    if (format != NULL) {
        ok(strcmp(info.format, format) == 0, "format %s, wanted %s",
           info.format, format);
    }
}

static void test_probe_errors(void)
{
    af_info   info;
    af_status status;

    begin("af_probe on a file that is not there");
    status = af_probe(fixture("no_such_file.wav"), &info);
    ok(status == AF_ERR_OPEN, "status %s, wanted nofile", af_status_string(status));

    begin("af_probe on a malformed file");
    status = af_probe(fixture("garbage.wav"), &info);
    ok(status != AF_OK, "a text file was accepted as audio");
    ok(status == AF_ERR_FORMAT, "status %s, wanted format", af_status_string(status));

    begin("af_probe with no path");
    status = af_probe(NULL, &info);
    ok(status == AF_ERR_ARGS, "status %s, wanted badargs", af_status_string(status));
}

static void test_truncated(void)
{
    af_info    info;
    af_status  status;
    af_stream *s;
    float     *buf;
    af_drain   d;

    if (!exists(fixture("truncated.wav"))) { skip("truncated.wav"); return; }

    begin("a truncated file reads short rather than crashing");

    status = af_probe(fixture("truncated.wav"), &info);
    if (status != AF_OK) {
        ok(1, "rejected outright, which is a fair answer");
        return;
    }

    ok(af_stream_new(&s, 1, FIXTURE_RATE) == AF_OK, "af_stream_new");
    ok(af_stream_open(s, fixture("truncated.wav"), &info) == AF_OK, "open");

    buf = scratch_buffer(FIXTURE_FRAMES * 2, 1);
    af_stream_set_running(s, 1);
    d = drain(s, buf, FIXTURE_FRAMES * 2, 256, 1, 3000);

    ok(!d.timed_out, "timed out draining a truncated file");
    ok(d.frames < (size_t)FIXTURE_FRAMES,
       "read %lu frames from a file cut short of %d",
       (unsigned long)d.frames, FIXTURE_FRAMES);

    free(buf);
    af_stream_free(s);
}

/* ------------------------------------------------------------------ */
/* Streaming                                                           */
/* ------------------------------------------------------------------ */

static void test_read_whole_file(const char *name, uint32_t channels)
{
    af_stream *s;
    af_info    info;
    float     *buf;
    af_drain   d;
    char       label[256];
    size_t     limit;

    if (!exists(fixture(name))) { skip(name); return; }

    snprintf(label, sizeof(label), "reading %s end to end", name);
    begin(label);

    ok(af_stream_new(&s, channels, FIXTURE_RATE) == AF_OK, "af_stream_new");
    ok(af_stream_open(s, fixture(name), &info) == AF_OK, "open");

    limit = (size_t)FIXTURE_FRAMES * 2;
    buf = scratch_buffer(limit, channels);

    af_stream_set_running(s, 1);
    d = drain(s, buf, limit, 64, channels, 5000);

    ok(!d.timed_out, "timed out");
    ok(d.eofs == 1, "eof reported %d times, wanted once", d.eofs);

    /* One frame of resampler history, and MP3 adds encoder padding. */
    ok(labs((long)d.frames - (long)FIXTURE_FRAMES) <= 8,
       "produced %lu frames, wanted %d",
       (unsigned long)d.frames, FIXTURE_FRAMES);

    if (channels == 1) {
        int lag = 0;
        double err = phase_error(buf + AF_PRIME, 512, (double)AF_PRIME, 1.0, &lag);
        ok(err < 0.02, "waveform is off by %.4f at lag %d", err, lag);
    }

    free(buf);
    af_stream_free(s);
}

static void test_seek(void)
{
    af_stream *s;
    af_info    info;
    float     *buf;
    af_drain   d;
    int        lag = 0;
    double     err;
    uint64_t   target = 7000;   /* not a whole number of cycles */

    begin("seeking, and the first block after it");

    ok(af_stream_new(&s, 1, FIXTURE_RATE) == AF_OK, "af_stream_new");
    ok(af_stream_open(s, fixture("sine_mono_44100_f32.wav"), &info) == AF_OK, "open");

    buf = scratch_buffer(4096, 1);
    af_stream_set_running(s, 1);

    /* Let the buffer fill with the start of the file, so that a seek that
     * failed to take would be caught handing back frames from around zero. */
    drain(s, buf, 2048, 64, 1, 2000);

    ok(af_stream_seek_frames(s, target) == AF_OK, "seek");

    d = drain(s, buf, 512, 64, 1, 2000);
    ok(!d.timed_out, "timed out after seeking");
    ok(d.frames == 512, "got %lu frames after seeking", (unsigned long)d.frames);

    err = phase_error(buf + AF_PRIME, 512 - AF_PRIME,
                      (double)(target + AF_PRIME), 1.0, &lag);
    ok(err < 0.02, "the block after the seek is off by %.4f (best lag %d): "
                   "stale samples, or the wrong position", err, lag);

    ok(labs((long)af_stream_tell_frames(s) - (long)(target + 512)) <= 64,
       "position reads %llu, wanted about %llu",
       (unsigned long long)af_stream_tell_frames(s),
       (unsigned long long)(target + 512));

    /* Seeking back and forth repeatedly is where a seek that has not settled
     * before the block it is asked for shows up. */
    {
        int i;
        int bad = 0;
        for (i = 0; i < 16; i++) {
            uint64_t where = (uint64_t)(1000 + i * 613);
            af_stream_seek_frames(s, where);
            d = drain(s, buf, 256, 64, 1, 2000);
            if (d.frames != 256) { bad++; continue; }
            if (phase_error(buf + AF_PRIME, 256 - AF_PRIME,
                            (double)(where + AF_PRIME), 1.0, NULL) >= 0.02) bad++;
        }
        ok(bad == 0, "%d of 16 repeated seeks came back wrong", bad);
    }

    begin("seeking past the end clamps, and reads as end of file");
    ok(af_stream_seek_frames(s, FIXTURE_FRAMES * 4) == AF_OK, "seek past the end");
    d = drain(s, buf, 512, 64, 1, 1000);
    ok(d.eofs == 1, "eof reported %d times after seeking past the end", d.eofs);
    ok(d.frames == 0, "%lu frames came back from beyond the end",
       (unsigned long)d.frames);

    begin("seeking with no file open");
    af_stream_close(s);
    ok(af_stream_seek_frames(s, 0) == AF_ERR_NOFILE, "seek without a file");

    free(buf);
    af_stream_free(s);
}

static void test_speed(void)
{
    af_stream *s;
    af_info    info;
    float     *buf;
    af_drain   d;

    begin("speed 2 halves the output length");

    ok(af_stream_new(&s, 1, FIXTURE_RATE) == AF_OK, "af_stream_new");
    ok(af_stream_open(s, fixture("sine_mono_44100_s16.wav"), &info) == AF_OK, "open");

    buf = scratch_buffer(FIXTURE_FRAMES, 1);
    af_stream_set_speed(s, 2.0);
    af_stream_set_running(s, 1);

    d = drain(s, buf, FIXTURE_FRAMES, 64, 1, 5000);
    ok(!d.timed_out, "timed out");
    ok(labs((long)d.frames - (long)(FIXTURE_FRAMES / 2)) <= 8,
       "produced %lu frames at speed 2, wanted about %d",
       (unsigned long)d.frames, FIXTURE_FRAMES / 2);

    /* At twice the rate the sine's period halves, from 100 frames to 50: each
     * output frame steps two frames through the file. */
    {
        int lag = 0;
        double err = phase_error(buf + AF_PRIME, 256,
                                 2.0 * AF_PRIME, 2.0, &lag);
        ok(err < 0.05, "the sine at speed 2 is off by %.4f at lag %d", err, lag);
    }

    free(buf);
    af_stream_free(s);

    begin("speed 0.5 doubles it");
    ok(af_stream_new(&s, 1, FIXTURE_RATE) == AF_OK, "af_stream_new");
    ok(af_stream_open(s, fixture("sine_mono_44100_s16.wav"), &info) == AF_OK, "open");
    buf = scratch_buffer(FIXTURE_FRAMES * 3, 1);
    af_stream_set_speed(s, 0.5);
    af_stream_set_running(s, 1);
    d = drain(s, buf, FIXTURE_FRAMES * 3, 64, 1, 8000);
    ok(!d.timed_out, "timed out");
    ok(labs((long)d.frames - (long)(FIXTURE_FRAMES * 2)) <= 8,
       "produced %lu frames at speed 0.5, wanted about %d",
       (unsigned long)d.frames, FIXTURE_FRAMES * 2);
    free(buf);
    af_stream_free(s);

    begin("a file at a different rate is resampled to the output rate");
    if (!exists(fixture("sine_mono_48000_s16.wav"))) {
        skip("sine_mono_48000_s16.wav");
    } else {
        ok(af_stream_new(&s, 1, 44100.0) == AF_OK, "af_stream_new");
        ok(af_stream_open(s, fixture("sine_mono_48000_s16.wav"), &info) == AF_OK, "open");
        ok(info.samplerate == 48000.0, "the file reports %g Hz", info.samplerate);
        buf = scratch_buffer(FIXTURE_FRAMES * 2, 1);
        af_stream_set_running(s, 1);
        d = drain(s, buf, FIXTURE_FRAMES * 2, 64, 1, 5000);
        ok(!d.timed_out, "timed out");
        /* 22050 frames of 48000 Hz material is 0.459 s, which is 20256 frames
         * at 44100 Hz. */
        ok(labs((long)d.frames - 20256L) <= 16,
           "produced %lu frames, wanted about 20256", (unsigned long)d.frames);
        free(buf);
        af_stream_free(s);
    }
}

static void test_loop(void)
{
    af_stream *s;
    af_info    info;
    float     *buf;
    af_drain   d;
    uint64_t   pos_before, pos_after;

    begin("looping runs past the end without reporting one");

    ok(af_stream_new(&s, 1, FIXTURE_RATE) == AF_OK, "af_stream_new");
    ok(af_stream_open(s, fixture("sine_mono_44100_s16.wav"), &info) == AF_OK, "open");

    buf = scratch_buffer((size_t)FIXTURE_FRAMES * 2 + 4096, 1);
    af_stream_set_loop(s, 1);
    af_stream_set_running(s, 1);

    d = drain(s, buf, FIXTURE_FRAMES + 4096, 64, 1, 8000);
    ok(!d.timed_out, "timed out");
    ok(d.eofs == 0, "eof reported %d times while looping", d.eofs);
    ok(d.frames == (size_t)FIXTURE_FRAMES + 4096,
       "produced %lu frames while looping", (unsigned long)d.frames);

    /* The position has to follow the file round, not run past its length. */
    pos_after = af_stream_tell_frames(s);
    ok(pos_after < (uint64_t)FIXTURE_FRAMES,
       "position reads %llu after wrapping a %d frame file",
       (unsigned long long)pos_after, FIXTURE_FRAMES);

    /* And the material after the wrap is the start of the file again. */
    {
        int lag = 0;
        double err = phase_error(buf + FIXTURE_FRAMES + AF_PRIME, 512,
                                 (double)AF_PRIME, 1.0, &lag);
        ok(err < 0.05, "the material after the loop point is off by %.4f", err);
    }

    begin("switching looping off lets the file end");
    pos_before = af_stream_tell_frames(s);
    ok(pos_before <= (uint64_t)FIXTURE_FRAMES, "position is inside the file");
    af_stream_set_loop(s, 0);
    d = drain(s, buf, FIXTURE_FRAMES * 2, 64, 1, 8000);
    ok(d.eofs == 1, "eof reported %d times after looping was switched off", d.eofs);

    free(buf);
    af_stream_free(s);
}

/* The idiom every patch reaches for first is [open sine.wav, run 1( into
 * [af.play~], with no gap between the two: the audio thread arrives before the
 * stream has read anything ahead. That is the buffer filling up, not the buffer
 * running dry, and telling the patch its audio dropped out before a single
 * frame has been delivered is wrong. */
static void test_cold_start_is_not_a_dropout(void)
{
    af_info info;
    float  *buf;
    int     trial;
    int     trials_with_reports = 0;

    begin("a cold start does not report a dropout");

    buf = scratch_buffer(4096, 1);

    for (trial = 0; trial < 20; trial++) {
        af_stream *s;
        int reports = 0;
        int i;

        ok(af_stream_new(&s, 1, FIXTURE_RATE) == AF_OK, "af_stream_new");
        ok(af_stream_open(s, fixture("sine_mono_44100_s16.wav"), &info) == AF_OK,
           "open");

        /* No settling time anywhere: this is the point of the test. */
        af_stream_set_running(s, 1);
        for (i = 0; i < 8; i++) {
            af_stream_read(s, buf, 64);
            if (af_stream_take_events(s) & AF_EVENT_UNDERFLOW) reports++;
        }
        if (reports > 0) trials_with_reports++;

        af_stream_free(s);
    }

    ok(trials_with_reports == 0,
       "%d of 20 cold starts reported underflow before delivering a frame",
       trials_with_reports);

    free(buf);
}

/* Landing somewhere that has not been read from disk yet is the same thing
 * again: the buffer is refilling, not running dry. */
static void test_seek_into_unbuffered_is_not_a_dropout(void)
{
    af_stream *s;
    af_info    info;
    float     *buf;
    int        trial;
    int        trials_with_reports = 0;

    begin("a seek into an unbuffered region does not report a dropout");

    ok(af_stream_new(&s, 1, FIXTURE_RATE) == AF_OK, "af_stream_new");
    ok(af_stream_open(s, fixture("sine_mono_44100_s16.wav"), &info) == AF_OK, "open");

    buf = scratch_buffer(4096, 1);
    af_stream_set_running(s, 1);
    drain(s, buf, 1024, 64, 1, 2000);
    af_stream_take_events(s);

    for (trial = 0; trial < 20; trial++) {
        int reports = 0;
        int i;

        ok(af_stream_seek_frames(s, (uint64_t)(500 + trial * 311)) == AF_OK, "seek");
        for (i = 0; i < 8; i++) {
            af_stream_read(s, buf, 64);
            if (af_stream_take_events(s) & AF_EVENT_UNDERFLOW) reports++;
        }
        if (reports > 0) trials_with_reports++;
    }

    ok(trials_with_reports == 0,
       "%d of 20 seeks reported underflow while re-buffering",
       trials_with_reports);

    free(buf);
    af_stream_free(s);
}

/* A stall that is genuinely the buffer running dry, so that it survives the
 * cold-start rule above.
 *
 * The stream is played normally first and settled on a whole block, so what
 * follows cannot be mistaken for a cold start. Then speed goes to its maximum:
 * every output frame now eats 32 frames of the file, so a block of 8192 wants a
 * quarter of a million frames, which is more than any read-ahead is going to
 * have ready. Looping stops the file simply ending instead. */
static void test_underflow(void)
{
    af_stream *s;
    af_info    info;
    float     *buf;
    int        short_reads = 0, reports = 0;
    int        i;

    begin("a stall is reported once, not once per block");

    ok(af_stream_new(&s, 1, FIXTURE_RATE) == AF_OK, "af_stream_new");
    ok(af_stream_open(s, fixture("sine_mono_44100_s16.wav"), &info) == AF_OK, "open");

    buf = scratch_buffer(8192, 1);
    af_stream_set_loop(s, 1);
    af_stream_set_running(s, 1);
    ok(settle(s, buf, 64), "the stream never got going");

    af_stream_set_speed(s, AF_SPEED_MAX);
    for (i = 0; i < 40; i++) {
        if (af_stream_read(s, buf, 8192) < 8192) short_reads++;
        if (af_stream_take_events(s) & AF_EVENT_UNDERFLOW) reports++;
    }
    ok(short_reads == 40, "%d of 40 reads fell short: nothing stalled", short_reads);
    ok(reports == 1, "%d underflow reports across one stall", reports);

    /* A seek ends the stall, so the next one is a new one. */
    ok(af_stream_seek_frames(s, 0) == AF_OK, "seek");
    af_stream_set_speed(s, 1.0);
    ok(settle(s, buf, 64), "the stream never got going again");

    af_stream_set_speed(s, AF_SPEED_MAX);
    short_reads = reports = 0;
    for (i = 0; i < 40; i++) {
        if (af_stream_read(s, buf, 8192) < 8192) short_reads++;
        if (af_stream_take_events(s) & AF_EVENT_UNDERFLOW) reports++;
    }
    ok(short_reads == 40, "%d of 40 reads fell short in the second stall", short_reads);
    ok(reports == 1, "%d underflow reports across the second stall", reports);

    free(buf);
    af_stream_free(s);
}

/* Pd's sample rate can change under an object that is already playing -- a
 * different device, or a patch reopened at another rate. The engine is built
 * for one rate, so this is the one message that rebuilds it, and the file has
 * to come back where it was. */
static void test_output_samplerate_change(void)
{
    af_stream *s;
    af_info    info;
    float     *buf;
    af_drain   d;
    uint64_t   before, after;

    begin("changing the output rate keeps the file and the position");

    ok(af_stream_new(&s, 1, FIXTURE_RATE) == AF_OK, "af_stream_new");
    ok(af_stream_open(s, fixture("sine_mono_44100_s16.wav"), &info) == AF_OK, "open");

    buf = scratch_buffer(8192, 1);
    af_stream_set_running(s, 1);
    d = drain(s, buf, 4096, 64, 1, 3000);
    ok(d.frames == 4096, "got %lu frames before the rate changed",
       (unsigned long)d.frames);
    before = af_stream_tell_frames(s);

    af_stream_set_output_samplerate(s, 48000.0);

    ok(af_stream_info(s, &info) == AF_OK, "the file is still open");
    ok(info.samplerate == FIXTURE_RATE, "info still describes the file, at %g",
       info.samplerate);
    ok(labs((long)af_stream_tell_frames(s) - (long)before) <= 64,
       "the position moved from %llu to %llu",
       (unsigned long long)before,
       (unsigned long long)af_stream_tell_frames(s));

    /* The file is reopened and sought behind this, so let it settle before
     * measuring what comes out. */
    drain(s, buf, 512, 64, 1, 3000);
    before = af_stream_tell_frames(s);

    /* 4800 frames at 48000 Hz is 4410 frames of a 44100 Hz file. */
    d = drain(s, buf, 4800, 64, 1, 3000);
    ok(!d.timed_out, "timed out after the rate changed");
    ok(d.frames == 4800, "got %lu frames at the new rate", (unsigned long)d.frames);

    after = af_stream_tell_frames(s);
    ok(labs((long)(after - before) - 4410L) <= 64,
       "the position advanced by %ld file frames, wanted about 4410",
       (long)(after - before));

    {
        int lag = 0;
        double err = phase_error(buf + AF_PRIME, 512, (double)(before + AF_PRIME),
                                 FIXTURE_RATE / 48000.0, &lag);
        ok(err < 0.05, "the sine after the rate change is off by %.4f at lag %d",
           err, lag);
    }

    free(buf);
    af_stream_free(s);
}

static void test_open_replaces(void)
{
    af_stream *s;
    af_info    info;
    float     *buf;
    af_status  status;

    begin("opening a second file replaces the first and stops playback");

    ok(af_stream_new(&s, 1, FIXTURE_RATE) == AF_OK, "af_stream_new");
    ok(af_stream_open(s, fixture("sine_mono_44100_s16.wav"), &info) == AF_OK, "open");

    buf = scratch_buffer(4096, 1);
    af_stream_set_running(s, 1);
    drain(s, buf, 2048, 64, 1, 2000);

    ok(af_stream_open(s, fixture("sine_mono_48000_s16.wav"), &info) == AF_OK,
       "second open");
    ok(info.samplerate == 48000.0, "info follows the new file");
    ok(af_stream_read(s, buf, 64) == 0, "playback did not stop");
    ok(af_stream_tell_frames(s) == 0, "the position did not go back to zero");

    begin("a failed open leaves the file that was open alone");
    status = af_stream_open(s, fixture("no_such_file.wav"), &info);
    ok(status == AF_ERR_OPEN, "status %s", af_status_string(status));
    ok(af_stream_info(s, &info) == AF_OK, "the previous file is still open");
    ok(info.samplerate == 48000.0, "and it is still the same one");

    begin("close, and what happens after it");
    af_stream_close(s);
    ok(af_stream_info(s, &info) == AF_ERR_NOFILE, "info after close");
    af_stream_set_running(s, 1);
    ok(af_stream_read(s, buf, 64) == 0, "reading after close produced frames");

    free(buf);
    af_stream_free(s);
}

static void test_channels(void)
{
    af_stream *s;
    af_info    info;
    float     *buf;
    af_drain   d;

    if (!exists(fixture("sine_stereo_44100_s16.wav"))) {
        skip("sine_stereo_44100_s16.wav");
        return;
    }

    begin("a stereo file into two channels keeps them apart");

    ok(af_stream_new(&s, 2, FIXTURE_RATE) == AF_OK, "af_stream_new");
    ok(af_stream_open(s, fixture("sine_stereo_44100_s16.wav"), &info) == AF_OK, "open");
    ok(info.channels == 2, "channels %u", info.channels);

    buf = scratch_buffer(4096, 2);
    af_stream_set_running(s, 1);
    d = drain(s, buf, 1024, 64, 2, 3000);
    ok(d.frames == 1024, "got %lu frames", (unsigned long)d.frames);

    /* The fixture inverts its second channel. */
    {
        double worst = 0.0;
        size_t i;
        for (i = 8; i < 1024; i++) {
            double err = fabs((double)buf[i * 2] + (double)buf[i * 2 + 1]);
            if (err > worst) worst = err;
        }
        ok(worst < 0.01, "the two channels are not mirrored: off by %.4f", worst);
    }

    free(buf);
    af_stream_free(s);
}

/* The reason this matters: [af.play~] and [af.info] are meant to answer with
 * the same four elements for the same file. A decoder configured for playback
 * describes the playback, so the two would drift apart without care. */
static void test_info_describes_the_file(void)
{
    af_stream *s;
    af_info    stream_info, probe_info;

    if (!exists(fixture("sine_stereo_44100_s16.wav"))) {
        skip("sine_stereo_44100_s16.wav");
        return;
    }

    begin("info describes the file, not the playback settings");

    /* One channel out, two in, and the file's own rate unlike the output's. */
    ok(af_stream_new(&s, 1, 22050.0) == AF_OK, "af_stream_new");
    ok(af_stream_open(s, fixture("sine_stereo_44100_s16.wav"), &stream_info) == AF_OK,
       "open");
    ok(af_probe(fixture("sine_stereo_44100_s16.wav"), &probe_info) == AF_OK, "probe");

    ok(stream_info.channels == probe_info.channels,
       "channels: the stream says %u, the file says %u",
       stream_info.channels, probe_info.channels);
    ok(stream_info.samplerate == probe_info.samplerate,
       "samplerate: the stream says %g, the file says %g",
       stream_info.samplerate, probe_info.samplerate);
    ok(stream_info.frames == probe_info.frames,
       "frames: the stream says %llu, the file says %llu",
       (unsigned long long)stream_info.frames,
       (unsigned long long)probe_info.frames);
    ok(strcmp(stream_info.format, probe_info.format) == 0,
       "format: the stream says %s, the file says %s",
       stream_info.format, probe_info.format);

    /* And `info` on the open file has to say the same thing again. */
    ok(af_stream_info(s, &stream_info) == AF_OK, "info");
    ok(stream_info.channels == probe_info.channels, "info channels %u",
       stream_info.channels);

    af_stream_free(s);
}

/* The audio thread can be inside a block when a file is replaced or the object
 * goes away; both have to wait for it before releasing anything. */
static void test_teardown_while_playing(void)
{
    af_stream *s;
    af_info    info;
    float     *buf;
    int        i;

    begin("closing and freeing while the stream is reading ahead");

    buf = scratch_buffer(4096, 1);

    for (i = 0; i < 8; i++) {
        ok(af_stream_new(&s, 1, FIXTURE_RATE) == AF_OK, "af_stream_new");
        ok(af_stream_open(s, fixture("sine_mono_44100_s16.wav"), &info) == AF_OK,
           "open");
        af_stream_set_loop(s, 1);
        af_stream_set_running(s, 1);
        af_stream_read(s, buf, 64);

        /* No settling time on purpose: the stream is most likely to be
         * mid-read right now. */
        if (i % 2) af_stream_close(s);
        af_stream_free(s);
    }
    ok(1, "eight streams opened and torn down mid-read");

    free(buf);
}

static void test_construction_errors(void)
{
    af_stream *s = NULL;

    begin("construction rejects what it cannot do");
    ok(af_stream_new(&s, 0, FIXTURE_RATE) == AF_ERR_ARGS, "zero channels");
    ok(af_stream_new(NULL, 2, FIXTURE_RATE) == AF_ERR_ARGS, "no out pointer");

    ok(af_stream_new(&s, 2, FIXTURE_RATE) == AF_OK, "af_stream_new");
    ok(af_stream_open(s, fixture("garbage.wav"), NULL) == AF_ERR_FORMAT,
       "opening a malformed file");
    ok(af_stream_open(s, NULL, NULL) == AF_ERR_ARGS, "opening nothing");
    af_stream_free(s);

    /* Freeing a stream that never opened anything has to join cleanly too. */
    ok(af_stream_new(&s, 1, FIXTURE_RATE) == AF_OK, "af_stream_new");
    af_stream_free(s);
    af_stream_free(NULL);
    ok(1, "freeing an unused stream");
}

/* ------------------------------------------------------------------ */

int main(int argc, char **argv)
{
    if (argc > 1) g_dir = argv[1];

    /* No fixtures means no Python at configure time. Nothing here can run,
     * and every case would fail for want of a file. */
    if (!exists(fixture("sine_mono_44100_s16.wav"))) {
        printf("no fixtures in %s: skipping\n", g_dir);
        return 77;
    }

    printf("pd-audiofile core tests, fixtures in %s\n\n", g_dir);

    probe_case("sine_mono_44100_s16.wav",   44100.0, FIXTURE_FRAMES, 1, "s16");
    probe_case("sine_mono_44100_f32.wav",   44100.0, FIXTURE_FRAMES, 1, "f32");
    probe_case("sine_stereo_44100_s16.wav", 44100.0, FIXTURE_FRAMES, 2, "s16");
    probe_case("sine_mono_48000_s16.wav",   48000.0, FIXTURE_FRAMES, 1, "s16");
    probe_case("sine_mono_44100_s16.aiff",  44100.0, FIXTURE_FRAMES, 1, "s16");
    probe_case("sine_mono_44100_s24.aiff",  44100.0, FIXTURE_FRAMES, 1, "s24");
    probe_case("trailing_chunk.wav",        44100.0, FIXTURE_FRAMES, 1, "s16");
    probe_case("sine_mono_44100.flac",      44100.0, FIXTURE_FRAMES, 1, NULL);
    probe_case("sine_mono_44100.mp3",       44100.0, 0,              1, NULL);
    probe_case("sine_mono_44100.ogg",       44100.0, 0,              1, NULL);

    test_probe_errors();
    test_truncated();

    test_read_whole_file("sine_mono_44100_s16.wav",  1);
    test_read_whole_file("sine_mono_44100_f32.wav",  1);
    test_read_whole_file("sine_mono_44100_s16.aiff", 1);
    test_read_whole_file("sine_mono_44100_s24.aiff", 1);
    test_read_whole_file("trailing_chunk.wav",       1);
    test_read_whole_file("sine_mono_44100.flac",     1);

    test_channels();
    test_seek();
    test_speed();
    test_loop();
    test_cold_start_is_not_a_dropout();
    test_seek_into_unbuffered_is_not_a_dropout();
    test_underflow();
    test_output_samplerate_change();
    test_open_replaces();
    test_info_describes_the_file();
    test_teardown_while_playing();
    test_construction_errors();

    printf("\n%d passed, %d failed, %d skipped\n", g_pass, g_fail, g_skip);
    return g_fail == 0 ? 0 : 1;
}
